import { Slider, VerticalBox } from "std-widgets.slint";
import { ReverbPanel } from "reverb_panel.slint";
import { MixerPanel } from "mixer_panel.slint";

export component MainWindow inherits Window {
    title: "neosynth";
    preferred-width: 480px;
    preferred-height: 760px;

    callback gain-changed(float);

    callback reverb-size-changed(float);
    callback reverb-feedback-changed(float);
    callback reverb-balance-changed(float);
    callback reverb-pre-delay-changed(float);
    callback reverb-hpf-changed(float);
    callback reverb-lpf-changed(float);
    callback reverb-chorus-changed(float);
    callback reverb-send-changed(float);

    callback mixer-dry-changed(float);
    callback mixer-reverb-changed(float);
    callback mixer-level-changed(float);

    in-out property <float> gain: 1.0;

    VerticalBox {
        Text {
            text: "Linear gain: " + root.gain;
            horizontal-alignment: center;
            font-size: 16px;
        }
        Slider {
            minimum: 0.0;
            maximum: 2.0;
            value: root.gain;
            changed(v) => {
                root.gain = v;
                root.gain-changed(v);
            }
        }
        ReverbPanel {
            size-changed(v) => { root.reverb-size-changed(v); }
            feedback-changed(v) => { root.reverb-feedback-changed(v); }
            balance-changed(v) => { root.reverb-balance-changed(v); }
            pre-delay-changed(v) => { root.reverb-pre-delay-changed(v); }
            hpf-changed(v) => { root.reverb-hpf-changed(v); }
            lpf-changed(v) => { root.reverb-lpf-changed(v); }
            chorus-changed(v) => { root.reverb-chorus-changed(v); }
            send-changed(v) => { root.reverb-send-changed(v); }
        }
        MixerPanel {
            dry-changed(v) => { root.mixer-dry-changed(v); }
            reverb-changed(v) => { root.mixer-reverb-changed(v); }
            level-changed(v) => { root.mixer-level-changed(v); }
        }
    }
}
